version: '3'
services: 
    web:
        image: centos:7
        container_name: nginx
        networks: 
            - test_net
        tty: true
    db:
        image: centos:7
        container_name: mysql
        networks: 
            - test_net
        environment: 
            - MYSQL_ROOT_PASSWORD=12345678
        tty: true
networks: 
    test_net: