version: '3'
services: 
    web:
        image: nginx:alpine
        container_name: nginx
        networks: 
            - test_net
    db:
        image: mysql:5.7
        container_name: mysql
        networks: 
            - test_net
networks: 
    test_net: